baseURL:
publishDir: "docs"
title: Portlolio
paginate: 5
theme: charlolamode

menu:
    main:
        - name: Contact
          url: /contact/
          weight: 20
        - name: Works
          url: /works/
          weight: 10
        - name: About 
          url: /about/
          weight: 1

params:
    author: Kinankomoti

    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:

        enabled: true
        title: Kinankomoti 
        description: |

          Graphics Engineer

          就活中

          C++/GLSL/Unity HLSL

        imageUrl: "/images/profile.png"
        imageTitle: my image

    mainSections:
      - Work

    socialIcons:
        - name: github
          url: "https://github.com/kinakomoti-321"
        - name: twitter
          url: "https://twitter.com/Kinakomoti2357"
        - name: blog
          url: "https://kinakomoti321.hatenablog.com/archive"

    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

